### ISSUE TITLE
TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki-plugin-linkmap#9]
The linkmap plugin is incompatible with wiki 0.21.0. After upgrading https://github.com/federated-wiki/wiki-docker-plugins/commit/72e9b5db422f7f505bcdcf2257b186e0b0f7ec32 it throws

```
2020-02-13T19:27:12.307842237Z app[web.1]: /usr/local/lib/node_modules/wiki/node_modules/wiki-plugin-linkmap/server/server.js:41
2020-02-13T19:27:12.307857700Z app[web.1]:             return item.text.match(/\[\[([^\]]+)\]\]/g);
2020-02-13T19:27:12.307860973Z app[web.1]:                              ^
2020-02-13T19:27:12.307863415Z app[web.1]: 
2020-02-13T19:27:12.307865443Z app[web.1]: TypeError: Cannot read property 'match' of undefined
2020-02-13T19:27:12.307867630Z app[web.1]:     at /usr/local/lib/node_modules/wiki/node_modules/wiki-plugin-linkmap/server/server.js:41:30
2020-02-13T19:27:12.307869914Z app[web.1]:     at findLinks (/usr/local/lib/node_modules/wiki/node_modules/wiki-plugin-linkmap/server/server.js:43:9)
2020-02-13T19:27:12.307877435Z app[web.1]:     at /usr/local/lib/node_modules/wiki/node_modules/wiki-plugin-linkmap/server/server.js:72:38
2020-02-13T19:27:12.307879594Z app[web.1]:     at /usr/local/lib/node_modules/wiki/node_modules/wiki-plugin-linkmap/server/server.js:28:14
2020-02-13T19:27:12.307881590Z app[web.1]:     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
2020-02-13T19:27:12.307883594Z app[web.1]: 
```

followed by

```
2020-02-13T19:27:12.312273364Z app[web.1]: server unexpectly exitted, 12 (1)
```

**Comment by paul90** [comment]
the linkmap plug-in was removed from the standard set of plugins back in 2016. As noted elsewhere, https://github.com/fedwiki/wiki/pull/127#issuecomment-534587061, this plug-in might be looked at again.
